import type { Workbook } from "@/types/workbook"

export const mockWorkbook: Workbook = {
  id: "wb-123",
  name: "empty-sheet.xlsx",
  sheets: [
    {
      id: "sh-abc",
      name: "Sheet1",
      data: [
        ["", "", "", "DAY 1 - TUESDAY, AUGUST 5, 2025", "", "", "", ""],
        ["", "", "", "Cambridge Exploration: Harvard, MIT & Historic Boston", "", "", "", ""],
        ["", "", "", "", "", "", "", ""],
        ["", "Time", "Activity", "Location", "Duration", "Cost", "Category", "Notes"],
        [
          "5",
          "9:00 AM",
          "Breakfast at Henrietta's Table",
          "1 Bennett St, Cambridge",
          "1.5 hours",
          "$30",
          "Dining",
          "Farm-to-table breakfast",
        ],
        [
          "6",
          "10:30 AM",
          "Harvard University Campus Tour",
          "Harvard Square",
          "1.5 hours",
          "$0",
          "Historic/Culture",
          "Student-led tours",
        ],
        [
          "7",
          "12:00 PM",
          "Harvard Museum of Natural History",
          "26 Oxford St, Cambridge",
          "1.5 hours",
          "$15",
          "Museum",
          "Sea Monsters exhibition",
        ],
        [
          "8",
          "1:30 PM",
          "Lunch at Shepard Restaurant",
          "1 Shepard St, Cambridge",
          "1.5 hours",
          "$35",
          "Dining",
          "Wood-fired pizzas",
        ],
        [
          "9",
          "3:00 PM",
          "Walk from Harvard to MIT",
          "via Massachusetts Ave",
          "45 min",
          "$0",
          "Walk/Explore",
          "Pass through Central Square",
        ],
        ["10", "3:45 PM", "MIT Museum", "Kendall Square", "1.5 hours", "$18", "Museum", "Reimagined museum showcase"],
        [
          "11",
          "5:15 PM",
          "Toscanini's Ice Cream",
          "899 Main St, Cambridge",
          "30 min",
          "$6",
          "Dessert",
          "Famous for unique flavors",
        ],
        ["12", "6:00 PM", "Check-in at Hotel Cambridge", "Cambridge", "1 hour", "$0", "Accommodation", "Check-in only"],
        [
          "13",
          "7:30 PM",
          "Dinner at Harvest",
          "44 Brattle St, Cambridge",
          "2 hours",
          "$65",
          "Fine Dining",
          "Farm-to-table, garden terrace",
        ],
        [
          "14",
          "9:30 PM",
          "Nightcap at The Longfellow Bar",
          "40 Brattle St Cambridge",
          "1.5 hours",
          "$20",
          "Nightlife",
          "Craft cocktails",
        ],
        ["15", "", "", "", "", "", "", ""],
        ["16", "Day 1 Total:", "", "", "", "$", "179.00", ""],
        ["17", "", "", "", "", "", "", ""],
        ["18", "", "", "", "DAY 2 - WEDNESDAY, AUGUST 6, 2025", "", "", "", ""],
        ["19", "", "", "", "Historic Boston: Freedom Trail, Museums & North End", "", "", "", ""],
        ["20", "", "", "", "", "", "", "", ""],
        [
          "21",
          "8:30 AM",
          "Breakfast at Thinking Cup",
          "165 Tremont St, Boston",
          "1 hour",
          "$15",
          "Dining",
          "Popular coffee shop",
        ],
        [
          "22",
          "9:30 AM",
          "Freedom Trail Walking Tour",
          "Boston Common Start",
          "2 hours",
          "$15",
          "Historic Tour",
          "Costumed guide tour",
        ],
        [
          "23",
          "11:30 AM",
          "Paul Revere House",
          "19 North Square, Boston",
          "45 min",
          "$6",
          "Historic Site",
          "17th century home",
        ],
        [
          "24",
          "12:30 PM",
          "Lunch at Neptune Oyster",
          "63 Salem St, North End",
          "1.5 hours",
          "$45",
          "Seafood",
          "Famous lobster rolls",
        ],
        [
          "25",
          "2:00 PM",
          "Explore North End & Get Cannoli",
          "Hanover St, North End",
          "1 hour",
          "$8",
          "Food/Walk",
          "Italian neighborhood",
        ],
        [
          "26",
          "3:00 PM",
          "Museum of Fine Arts",
          "465 Huntington Ave",
          "2.5 hours",
          "$25",
          "Art Museum",
          "Van Gogh exhibition",
        ],
        ["27", "5:30 PM", "Quick stop at hotel", "Cambridge", "1 hour", "$0", "Rest", "Refresh before dinner"],
      ],
    },
    {
      id: "sh-def",
      name: "Itinerary",
      data: [
        ["Budget Category", "Planned Amount"],
        ["Accommodation", 200],
        ["Food & Dining", 300],
        ["Activities", 150],
        ["Transportation", 100],
      ],
    },
    {
      id: "sh-ghi",
      name: "Budget",
      data: [
        ["Item", "Cost"],
        ["Hotel (2 nights)", 400],
        ["Meals", 280],
        ["Museum tickets", 64],
        ["Transportation", 50],
      ],
    },
    {
      id: "sh-jkl",
      name: "Reservations",
      data: [
        ["Restaurant", "Date", "Time", "Party Size"],
        ["Henrietta's Table", "8/5/2025", "9:00 AM", 2],
        ["Harvest", "8/5/2025", "7:30 PM", 2],
        ["Neptune Oyster", "8/6/2025", "12:30 PM", 2],
      ],
    },
  ],
}
